"""verification_doc_url added in Website

Revision ID: 805d9a22c816
Revises: 475a9d71ed50
Create Date: 2019-03-01 16:53:55.630972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805d9a22c816'
down_revision = '475a9d71ed50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website', sa.Column('verification_doc_url', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website', 'verification_doc_url')
    # ### end Alembic commands ###
